kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-minikube-2
  namespace: default
  labels:
    run: hello-minikube-2
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello-minikube-2
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-minikube-2
    spec:
      containers:
        - name: hello-minikube-2
          image: 'registry.cn-qingdao.aliyuncs.com/k8slast/echoserver:1.10'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
